require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContentPagesController do

  # This should return the minimal set of attributes required to create a valid
  # ContentPage. As you add validations to ContentPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all content_pages as @content_pages" do
      content_page = ContentPage.create! valid_attributes
      get :index
      assigns(:content_pages).should eq([content_page])
    end
  end

  describe "GET show" do
    it "assigns the requested content_page as @content_page" do
      content_page = ContentPage.create! valid_attributes
      get :show, :id => content_page.id.to_s
      assigns(:content_page).should eq(content_page)
    end
  end

  describe "GET new" do
    it "assigns a new content_page as @content_page" do
      get :new
      assigns(:content_page).should be_a_new(ContentPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested content_page as @content_page" do
      content_page = ContentPage.create! valid_attributes
      get :edit, :id => content_page.id.to_s
      assigns(:content_page).should eq(content_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContentPage" do
        expect {
          post :create, :content_page => valid_attributes
        }.to change(ContentPage, :count).by(1)
      end

      it "assigns a newly created content_page as @content_page" do
        post :create, :content_page => valid_attributes
        assigns(:content_page).should be_a(ContentPage)
        assigns(:content_page).should be_persisted
      end

      it "redirects to the created content_page" do
        post :create, :content_page => valid_attributes
        response.should redirect_to(ContentPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved content_page as @content_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContentPage.any_instance.stub(:save).and_return(false)
        post :create, :content_page => {}
        assigns(:content_page).should be_a_new(ContentPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContentPage.any_instance.stub(:save).and_return(false)
        post :create, :content_page => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested content_page" do
        content_page = ContentPage.create! valid_attributes
        # Assuming there are no other content_pages in the database, this
        # specifies that the ContentPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContentPage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => content_page.id, :content_page => {'these' => 'params'}
      end

      it "assigns the requested content_page as @content_page" do
        content_page = ContentPage.create! valid_attributes
        put :update, :id => content_page.id, :content_page => valid_attributes
        assigns(:content_page).should eq(content_page)
      end

      it "redirects to the content_page" do
        content_page = ContentPage.create! valid_attributes
        put :update, :id => content_page.id, :content_page => valid_attributes
        response.should redirect_to(content_page)
      end
    end

    describe "with invalid params" do
      it "assigns the content_page as @content_page" do
        content_page = ContentPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContentPage.any_instance.stub(:save).and_return(false)
        put :update, :id => content_page.id.to_s, :content_page => {}
        assigns(:content_page).should eq(content_page)
      end

      it "re-renders the 'edit' template" do
        content_page = ContentPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContentPage.any_instance.stub(:save).and_return(false)
        put :update, :id => content_page.id.to_s, :content_page => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested content_page" do
      content_page = ContentPage.create! valid_attributes
      expect {
        delete :destroy, :id => content_page.id.to_s
      }.to change(ContentPage, :count).by(-1)
    end

    it "redirects to the content_pages list" do
      content_page = ContentPage.create! valid_attributes
      delete :destroy, :id => content_page.id.to_s
      response.should redirect_to(content_pages_url)
    end
  end

end
